apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.appName }}
  name: spark-history-server
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: spark-history-server
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.appName }}
  name: spark-master-ui
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: spark-master-ui
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.appName }}
  name: spark-notebook
spec:
  port:
    targetPort: 8888-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: spark-notebook
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.appName }}
  name: dagster
spec:
  port:
    targetPort: 3000-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: spark-notebook
---
