apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: spark-history-server
spec:
  ports:
  - port: 8087
    protocol: TCP
    targetPort: 8087
  selector:
    app: {{ .Values.appName }}
    role: spark-history-server
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: spark-master
spec:
  ports:
  - port: 7077
    protocol: TCP
    targetPort: 7077
  selector:
    app: {{ .Values.appName }}
    role: spark-master
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: spark-master-ui
spec:
  ports:
  - port: 8087
    protocol: TCP
    targetPort: 8087
  selector:
    app: {{ .Values.appName }}
    role: spark-master
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: spark-notebook
spec:
  ports:
  - name: 4040-tcp
    port: 4040
    protocol: TCP
    targetPort: 4040
  - name: 8888-tcp
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: 2222-tcp
    port: 2222
    protocol: TCP
    targetPort: 2222
  - name: 7777-tcp
    port: 7777
    protocol: TCP
    targetPort: 7777
  - name: 9999-tcp
    port: 9999
    protocol: TCP
    targetPort: 9999
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ .Values.appName }}
    role: spark-notebook
